### PR TITLE
Fix unexpected token error when used with react-native's AsyncStorage

### PR DESCRIPTION
**Pull request by ianberinger**
I get the following error when using this package with the AsyncStorage engine:
simulator screen shot jan 13 2017 10 01 14 pm

This PR fixes this issue.
transform-compress does something similar: https://github.com/rt2zz/redux-persist-transform-compress/blob/master/index.js#L7

### CODE REVIEW

**Comment by maxdeviant** [comment]
@ianberinger Sorry for not getting back to you on this.

I agree that this is a problem, but after glancing at the code, I think I would prefer to fix it a different way (because it seems like there was actually a bug introduced when I rewrote some of the lib).

I just haven't had the time to look at it yet.

**Comment by ianberinger** [comment]
@maxdeviant That's alright with me. Let me know if there's anything I can do to help you fix this.

**Comment by maxdeviant** [comment]
@ianberinger After looking at this more, I am not sure I understand what the problem is.

I see that your fix just involved calling `JSON.stringify` on the state, but this is already being performed inside of the `makeEncryptor` helper function:

[src/helpers.js](https://github.com/maxdeviant/redux-persist-transform-encrypt/blob/master/src/helpers.js#L4-L6):

```js
export const makeEncryptor = transform => (state, key) => {
  if (typeof state !== 'string') {
    state = stringify(state);
  }
  return transform(state);
};
```

And from my test coverage, it looks like it is calling stringify on the state before running the encryption.

I wonder if it is a problem with `json-stable-stringify` on React Native?

If you want, you could try swapping out the call to `stringify` with `JSON.stringify` to see if that fixes the issue.

**Comment by maxdeviant** [comment]
@ianberinger I added a React Native example [here](https://github.com/maxdeviant/redux-persist-transform-encrypt/tree/master/examples/ReactNativeExample), which seems to work without errors.

Are you using any other transforms in addition to `redux-persist-transform-encrypt`?

**Comment by ianberinger** [comment]
@maxdeviant Yes, I'm using `redux-persist-transform-compress` followed by `redux-persist-transform-encrypt`. I will take a look at your example & suggestion on the weekend.

**Comment by ianberinger** [comment]
@maxdeviant I can reproduce my original issue with your example by adding `redux-persist-transform-compress`:

```
import createCompressor from 'redux-persist-transform-compress';
```
...
```
persistStore(store, {
  storage: AsyncStorage,
  transforms: [
    createCompressor(),
    encryptor
  ]
});

```
simulator screen shot apr 8 2017 12 14 22 pm

Changing `stringify` to `JSON.stringify` doesn't help.

The error is caused by `JSON.parse` in https://github.com/maxdeviant/redux-persist-transform-encrypt/blob/master/src/sync.js#L12. This fails, because we don't have a valid JSON string (doublequotes are missing). 

In https://github.com/maxdeviant/redux-persist-transform-encrypt/blob/master/src/helpers.js#L5 `state` only gets stringified if it isn't `typeof string`. But a `typeof string` isn't automatically a JSON string.
In the case of `redux-persist-transform-compress`, `state` is already a string, but not a JSON string.

I think `stringify(state)` should always be called.  I changed by PR to reflect that.

**Comment by maxdeviant** [comment]
@ianberinger Thanks for the info.

The reason we don't stringify the state every time is that it can potentially be somewhat expensive for a very large state tree.

But it sounds like the compress middleware is not emitting a valid JSON string, so perhaps this is best fixed there?

**Comment by maxdeviant** [comment]
@ianberinger You do raise a good point about a string that passes the `typeof string` not necessarily being a JSON string. But since that latter is harder to check for, I think that the plugins for `redux-persist` should probably have some sort of established contract with each other.

Perhaps @rt2zz could weigh in on this?

**Pull request closed without merging**
